version: '3.8'
services:
  kafka:
    container_name: kafka-t
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/apt/kafka/kafka-logs
  mongodb:
    container_name: turkcell-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/dd

  inventorydb:
    container_name: inventorydb
    image: mysql
    ports:
      - "3302:3302"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL-TCP-PORT=3306
      - VIRTUAL_PORT=3306
    volumes:
      - inventorydb:/data/db

volumes:
  kafka_data:
  mongodb_data:
