version: '3.8'
services:
  kafka:
    container_name: kafka-t
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/apt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.102:9092

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-t2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports
  
  mongodb_filter:
    container_name: turkcell-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/dd
  mongodb_invoice:
    container_name: turkcell-invoicedb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/dd

  inventorydb:
    container_name: inventorydb
    image: mysql
    ports:
      - "3302:3302"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL-TCP-PORT=3306
      - VIRTUAL_PORT=3306
    volumes:
      - inventorydb:/data/db

volumes:
  kafka_data:
  mongodb_filter_data:
  mongodb_invoice_data:

