spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/NurYucel/config-server
  profiles:
    active: prod
server:
  port: 8888
